### ISSUE TITLE
order_with_respect_to with non-foreign keys

### ISSUE THREAD

**Issue by Hafnernuss** [django-ordered-model/django-ordered-model#298]
Hi,

Suppose I have the following model:

```py
class Training(models.Model):
   pass

class TrainingExercise(OrderedModel, models.Model):
  class StageChoices(models.IntegerChoices):
          WarmUp = 1,     
          MainPart = 2,     
          EndPart = 3, 

  training = models.ForeignKey(...)
  stage = models.PositiveSmallIntegerField(choices=StageChoices.choices)
  
  order_with_respect_to = ('training', 'stage)
```

This fails with `E005`, because `stage` is not a foreign key.
But why? I think this is a good use case for sub-ordering without foreign keys. Sure, I could put my "stages" into their own model, but this would create unnecessary overhead. And in the past, I think this sort-of worked.

to be clear, I would like to have the following:

TrainingExercise1: training 1, stage warm-up,  order 0
TrainingExercise2: training 1, stage warm-up,  order 1
TrainingExercise3: training 1, stage main-part order 0
TrainingExercise4: training 1, stage main-part order 1
TrainingExercise5: training 2, stage warm-up order 0
TrainingExercise6: training 2, stage main-part order 0

Or is this simply "unnecessary" because one could achieve the correct ordering in the queryset with this:
```py
    class Meta:
        ordering = ('stage', 'order')
```
I suspect it would ensure the correct odering, the only tradeoff would be, that the `order` index would be "incorrect", right?

**Comment by Hafnernuss** [comment]
I did a quick check, and `3.7.0` allows `order_with_respect_to` without foreign keys, and it appears to be working flawlessly. 
So I'm curious, what prompted the change and what might be the rationale for this.

**Comment by Hafnernuss** [comment]
> 

I am currently staying on `3.7.0`, and have encountered no problems so far.

**Comment by Eraldo** [comment]
> I am currently staying on `3.7.0`, and have encountered no problems so far.

Doing the same until I know how to proceed. (and eventually make my dependabot happy as well) 😄

**Comment by riconnon** [comment]
Same issue here.
We have a `DateTimeField` on our ordered model in our `order_with_respect_to`

**Comment by Hafnernuss** [comment]
Can someone from the maintainer team acknowledge that this in fact _is_ a bug that will be fixed? Because if this is intended behaviour, I'd have to make changes to my codebase. It'd be fine, I just want to know 😀

**Comment by JulianTenschert** [comment]
Same issue here. Version 3.7.2 includes a breaking change and should have been released as a new major version (e.g. v4.0.0).

**Comment by riconnon** [comment]
> Same issue here. Version 3.7.2 includes a breaking change and should have been released as a new major version (e.g. v4.0.0).

Even aside from the version... I think it's questionable whether this change should have been made.
I'm not sure I see the benefit it offers, and it blocks off some valid use-cases.

**Comment by shuckc** [comment]
Lets me talk you through the change. We know that `order_with_respect_to` (owrt) partitions the dataset so that we can have a separate numbering from zero within each partition, and one or more fields on the model defines which partition the object is in. Historically if you *changed* the values in those owrt fields, then the ordering was broken in both the new and old set.

In 3.7 with #198 we detect when owrt fields change value in order to perform the correct extra operations: handle as if the object was deleted from the old partition, then inserted into the new partition. In order to do this, we need to cache the old values of the fields on object construction, and inspect them again in `save()`. This was a minor release as a reasonably decent change and was backwards compatible.
 
I made improvements in 3.7.1 (fixing a false change detected when in the django admin) and again in 3.7.2 after realising it fetched the *entire* related object, which was a significant drag on performance (issue #286). The optimisation observed that *in the test suite*, we only have ForeignKey fields in owrt. Therefore we optimised the code to fetch only the ID of the FK rather than the object, and at the same time added the Error `E005` if a non-FK field is added to owrt.

Given that there clearly is some usage in the wild with non-FK fields, I'm happy to properly capture this behaviour in the tests and then fix the issue. Is the `TrainingExercise` the best example we have?

**Comment by shuckc** [comment]
This should be fixed on master if anyone can test it. This will be part of the 3.8 release.

**Comment by riconnon** [comment]
@shuckc my CI runs seem to pass using the tip of `master` now, which is a very positive sign!
Do you have a timescale for the release of 3.8?

**Comment by shuckc** [comment]
I wanted to have a fix for #295 ready for 3.8

**Comment by Eraldo** [comment]
Why was this closed?
Version 3.7.4 still throws an error instead of a warning. 🤔

**Comment by jrobichaud** [comment]
@Eraldo I believe it was closed because it is scheduled for 3.8 which is not released yet. 

Did you try using the latest commit of the master branch?

**Comment by Eraldo** [comment]
> Did you try using the latest commit of the master branch?
@jrobichaud I tried it using `v3.7.4` which according to the release notes did "relax" the error into a warning. However this is only true for fields on a related FK model not on the source model itself. At least from what I can tell from reading the source.
